# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 06:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import voiceadmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('other_names', models.CharField(blank=True, max_length=200)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('average_score', models.FloatField(null=True)),
                ('no_performances', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('other_names', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('final_score', models.FloatField(default=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voiceadmin.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', voiceadmin.models.ScoreField(validators=[django.core.validators.MaxValueValidator(100, message='Please enter a value less than 100')], verbose_name='score')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voiceadmin.Mentor')),
                ('performance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voiceadmin.Performance')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_formed', models.DateField(blank=True, null=True)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voiceadmin.Mentor')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voiceadmin.Team'),
        ),
    ]
