# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voiceadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='no_performances',
            new_name='no_scores',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='final_score',
            new_name='average_score',
        ),
        migrations.AddField(
            model_name='performance',
            name='no_scores',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='no_scores',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='other_names',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='performancescore',
            name='performance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_scores', to='voiceadmin.Performance'),
        ),
    ]
