# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voiceadmin', '0002_auto_20171202_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='average_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='voiceadmin.Team'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_performances', to='voiceadmin.Candidate'),
        ),
        migrations.AlterField(
            model_name='team',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voiceadmin.Mentor'),
        ),
    ]
