# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceadmin', '0003_auto_20171203_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='average_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
