# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiceadmin', '0004_auto_20171203_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancescore',
            name='score',
        ),
    ]
