# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 08:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import voiceadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceadmin', '0005_remove_performancescore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancescore',
            name='score',
            field=voiceadmin.models.ScoreField(default=0, validators=[django.core.validators.MaxValueValidator(100, message='Please enter a value less than 100')], verbose_name='score'),
        ),
    ]
